### ISSUE TITLE
NetBSD missing pkg_info

### ISSUE THREAD

**Issue by polluks** [Un1q32/pfetch#20]
```
\\`-______,----__     polluks@sdf
 \\        __,---`_   os     NetBSD 10.0
  \\       `.____     host   Supermicro X7DBT
   \\-______,----`-   uptime 7d 14h 18m
pkg_info: not found
./pfetch: arith: syntax error: "total_pkgs + count"
```
By the way
```
$ ls /usr/pkg/db/pkg | wc -l
    1127

**Comment by Un1q32** [comment]
Seems to work fine for me on this mostly fresh install. Is pkg_info not installed on your system or in your PATH? My understanding is that it's installed by default on every NetBSD system, the original pfetch didn't have a check for it either, though it wouldn't have caused as much of an issue since they handled package counting differently. I can add a check for pkg_info existing and that might fix the issue.  Also /usr/pkg/db/pkg doesn't seem to exist on my install, there is /usr/pkg/pkgdb that seems like it might be the same thing, but pkg_info seems fast enough that I don't think it would be worth it to have checks for certain common directories to use instead of just running pkg_info.

![2024-06-10-143606_hyprshot](https://github.com/Un1q32/pfetch/assets/57970114/44825f4d-9469-4f2f-b390-562c3f208ee0)

**Comment by Un1q32** [comment]
Try the latest commit and see if that fixes it.

**Comment by polluks** [comment]
What about non-root users? Thank you so far.
```
$ bash pfetch -d
\\`-______,----__     polluks@sdf
 \\        __,---`_   os     NetBSD 10.0
  \\       `.____     host   Supermicro X7DBT
   \\-______,----`-   uptime 8d 1h 4m
    \\                memory 13379M / 16382M
     \\
      \\

$ sh pfetch -d 
\\`-______,----__     polluks@sdf
 \\        __,---`_   os     NetBSD 10.0
  \\       `.____     host   Supermicro X7DBT
   \\-______,----`-   uptime 8d 1h 4m
pfetch: arith: syntax error: "total_pkgs + count"

**Comment by Un1q32** [comment]
seems /usr/sbin is in PATH on my install even for non-root.  pfetch still works fine.

**Comment by Un1q32** [comment]
damn you github

**Comment by Un1q32** [comment]
try latest commit

**Comment by polluks** [comment]
hmm, the same syntax error
```
$ echo $PATH
/bin:/usr/bin:/usr/pkg/bin:/usr/local/bin:/usr/pkg/games:/usr/pkg/X11R7/bin
```
I have only pkg-config

**Comment by Un1q32** [comment]
whats the output of `which pkg_info` (as root)

**Comment by Un1q32** [comment]
Oh wait I think I might have found the problem, try latest commit now

**Comment by polluks** [comment]
almost right
```
$ ./pfetch -d
\\`-______,----__     polluks@sdf
 \\        __,---`_   os     NetBSD 10.0
  \\       `.____     host   Supermicro X7DBT
   \\-______,----`-   uptime 8d 3h 5m
    \\                pkgs   1
     \\               memory 13800M / 16382M
      \\

**Comment by Un1q32** [comment]
what is the output of `pkg_info` and `which pkg_info`?

**Comment by polluks** [comment]
```
$ ls -l /usr/sbin/pkg_info
-r-xr-xr-x  1 root  wheel  108064 Aug  4  2022 /usr/sbin/pkg_info
$ /usr/sbin/pkg_info
$ pkg_info
zsh: command not found: pkg_info

**Comment by Un1q32** [comment]
What is the output of `PF_PACKAGE_MANAGERS=on pfetch -d`

**Comment by Un1q32** [comment]
looks like the 1 extra package is comming from cargo, not pkgsrc
